name: Build, Push Docker Images and Update GitOps Repo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get commit SHA
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ----------------------
    # Backend Image Build & Push with caching
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kindergarten-backend:${{ env.COMMIT_SHA }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kindergarten-backend:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kindergarten-backend:cache,mode=max

    # ----------------------
    # Frontend Image Build & Push with caching
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kindergarten-frontend:${{ env.COMMIT_SHA }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kindergarten-frontend:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/kindergarten-frontend:cache,mode=max

    # ----------------------
    # Update GitOps repo
    - name: Update GitOps Repo
      env:
        COMMIT_SHA: ${{ env.COMMIT_SHA }}
      run: |
        git config --global user.email "nabil@gmail.com"
        git config --global user.name "Nabil"

        git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/Nabil720/kindergarten-registry_k8s.git
        cd kindergarten-registry_k8s/k8s

        # Update image tags
        sed -i "s|image: .*kindergarten-backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/kindergarten-backend:${COMMIT_SHA}|" ./backend/deployment.yaml
        sed -i "s|image: .*kindergarten-frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/kindergarten-frontend:${COMMIT_SHA}|" ./frontend/deployment.yaml

        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update backend & frontend image tags to ${COMMIT_SHA}"
          git push origin main
        fi
